export interface CourseCatalogEntry {
  id: number;
  name: string;
  theme: string;
  description: string;
  topicCoverage: string[];
  badge?: string;
}

export const courseCatalog: CourseCatalogEntry[] = [
  {
    id: 1,
    name: "Syntax & Types",
    theme: "Starter Valley",
    description: "יסודות התחביר, משתנים, וטיפוסים בסיסיים ב-Swift.",
    topicCoverage: ["let", "var", "String", "Int", "Double", "Bool", "print", "comments", "interpolation", "type safety"],
    badge: "Syntax Survivor",
  },
  {
    id: 2,
    name: "Operators & Bool Logic",
    theme: "Logic Ridge",
    description: "אופרטורים, השוואות, ותנאים לוגיים מדויקים.",
    topicCoverage: ["operators", "assignment vs equality", "comparison", "Bool", "&&", "||", "precedence", "conditions"],
    badge: "Logic Solver",
  },
  {
    id: 3,
    name: "Control Flow",
    theme: "Forked Canyon",
    description: "שליטה בזרימת קוד עם if/switch/loops.",
    topicCoverage: ["if / else", "switch", "for-in", "while", "repeat-while", "break", "continue"],
    badge: "Flow Ranger",
  },
  {
    id: 4,
    name: "Functions",
    theme: "Echo Woods",
    description: "פונקציות, פרמטרים, החזרות וחתימות קריאה.",
    topicCoverage: ["func", "parameters", "return", "argument labels", "default values", "scope", "inout", "overloading"],
    badge: "Function Crafter",
  },
  {
    id: 5,
    name: "Optionals",
    theme: "Nil Caverns",
    description: "עבודה בטוחה עם Optional ו-unwrapping.",
    topicCoverage: ["Optional", "nil", "if let", "guard let", "optional chaining", "nil coalescing", "force unwrap"],
    badge: "Optional Survivor",
  },
  {
    id: 6,
    name: "Collections",
    theme: "Vault Plains",
    description: "Array / Dictionary / Set ופעולות טרנספורמציה בסיסיות.",
    topicCoverage: ["Array", "Dictionary", "Set", "iteration", "append/remove", "contains", "map", "filter", "reduce"],
    badge: "Collection Keeper",
  },
  {
    id: 7,
    name: "Enums",
    theme: "Variant Shrine",
    description: "Enums עם associated values ו-raw values.",
    topicCoverage: ["enum", "cases", "raw values", "associated values", "switch exhaustiveness"],
    badge: "Enum Oracle",
  },
  {
    id: 8,
    name: "Structs",
    theme: "Foundry District",
    description: "מודלים ב-struct, אתחול ו-value semantics.",
    topicCoverage: ["struct", "stored properties", "computed properties", "methods", "mutating", "init", "property observers"],
    badge: "Struct Architect",
  },
  {
    id: 9,
    name: "Classes",
    theme: "Ivory Keep",
    description: "ירושה, override, וזהות אובייקטים ב-class.",
    topicCoverage: ["class", "inheritance", "override", "final", "reference semantics", "identity", "deinit"],
    badge: "Class Commander",
  },
  {
    id: 10,
    name: "Protocols & Extensions",
    theme: "Rune Sanctum",
    description: "Protocol-oriented design ו-extension patterns.",
    topicCoverage: ["protocol", "conformance", "extension", "protocol-oriented basics", "composition"],
    badge: "Protocol Tactician",
  },
  {
    id: 11,
    name: "Closures",
    theme: "Closure Spire",
    description: "Closures, shorthand, capture ו-completion handlers.",
    topicCoverage: ["closures", "trailing closures", "shorthand args", "capture", "escaping", "completion handlers", "sorting closures"],
    badge: "Closure Master",
  },
  {
    id: 12,
    name: "Error Handling",
    theme: "Storm Coast",
    description: "טיפול בשגיאות עם throw, do/catch ו-Result.",
    topicCoverage: ["throw", "do/catch", "try", "try?", "try!", "Result", "error propagation"],
    badge: "Error Tamer",
  },
  {
    id: 13,
    name: "Generics",
    theme: "Template Forge",
    description: "Generic functions/types ו-type constraints.",
    topicCoverage: ["Generics", "generic functions", "generic types", "constraints", "where clause", "type parameters"],
    badge: "Generic Smith",
  },
  {
    id: 14,
    name: "Associated Types",
    theme: "Abstract Hall",
    description: "Protocols עם associatedtype ו-type erasure בסיסי.",
    topicCoverage: ["associatedtype", "protocol with associated types", "opaque types", "type erasure basics"],
    badge: "Abstraction Sage",
  },
  {
    id: 15,
    name: "ARC & Memory",
    theme: "Memory Vault",
    description: "ARC, retain cycles ו-weak/unowned.",
    topicCoverage: ["ARC", "retain cycle", "weak", "unowned", "reference lifecycle", "memory leaks"],
    badge: "Memory Guardian",
  },
  {
    id: 16,
    name: "Value vs Reference",
    theme: "Semantics Arena",
    description: "הבדלי התנהגות בין value types ל-reference types.",
    topicCoverage: ["value semantics", "reference semantics", "copy-on-write", "identity", "mutation behavior"],
    badge: "Semantics Judge",
  },
  {
    id: 17,
    name: "Concurrency Basics",
    theme: "Task Harbor",
    description: "async/await, Task ו-cancellation בסיסי.",
    topicCoverage: ["async/await", "Task", "await", "suspension points", "cancellation", "MainActor basics"],
    badge: "Async Navigator",
  },
  {
    id: 18,
    name: "Advanced Concurrency",
    theme: "Actor Citadel",
    description: "Actors, task groups, isolation ומניעת race conditions.",
    topicCoverage: ["actors", "task groups", "structured concurrency", "isolation", "Sendable", "race conditions"],
    badge: "Concurrency Champion",
  },
  {
    id: 19,
    name: "Standard Library Deep Dive",
    theme: "Library Nexus",
    description: "אלגוריתמים, מורכבויות ומבני נתונים ב-Standard Library.",
    topicCoverage: ["standard library", "algorithms", "complexity", "collections internals", "performance of operations"],
    badge: "Library Scholar",
  },
  {
    id: 20,
    name: "Modular Swift (SPM)",
    theme: "Module Harbor",
    description: "חלוקת קוד למודולים עם Swift Package Manager.",
    topicCoverage: ["Swift Package Manager", "modules", "targets", "package manifest", "API boundaries", "dependency management"],
    badge: "Module Builder",
  },
  {
    id: 21,
    name: "SwiftUI Foundations",
    theme: "Glass District",
    description: "Views בסיסיים, layout ומודיפיירים ב-SwiftUI.",
    topicCoverage: ["View", "Text", "Image", "stacks", "modifiers", "Button", "List", "Form"],
    badge: "SwiftUI Builder",
  },
  {
    id: 22,
    name: "SwiftUI State",
    theme: "State Garden",
    description: "ניהול state עם wrappers ב-SwiftUI.",
    topicCoverage: ["@State", "@Binding", "@ObservedObject", "@StateObject", "@EnvironmentObject", "@Observable", "data flow"],
    badge: "State Tamer",
  },
  {
    id: 23,
    name: "SwiftUI Navigation & UI Flows",
    theme: "Route City",
    description: "ניווט, sheet/alert ו-flow מסכים.",
    topicCoverage: ["NavigationStack", "NavigationPath", "sheet", "fullScreenCover", "alert", "deep links"],
    badge: "Flow Navigator",
  },
  {
    id: 24,
    name: "SwiftUI Architecture",
    theme: "Design Grid",
    description: "ארכיטקטורת פיצ'רים, reusable components ו-MVVM.",
    topicCoverage: ["MVVM", "feature boundaries", "dependency injection", "reusable components", "view models"],
    badge: "UI Architect",
  },
  {
    id: 25,
    name: "Networking",
    theme: "API Sea",
    description: "URLSession, Codable ו-layering של API client.",
    topicCoverage: ["URLSession", "Codable", "JSON decoding", "request building", "HTTP methods", "retry strategy", "API errors"],
    badge: "Network Runner",
  },
  {
    id: 26,
    name: "Persistence",
    theme: "Data Archive",
    description: "אחסון מקומי עם UserDefaults, files ו-SwiftData/Core Data.",
    topicCoverage: ["UserDefaults", "FileManager", "SwiftData", "Core Data basics", "local persistence", "migrations basics"],
    badge: "Data Keeper",
  },
  {
    id: 27,
    name: "Testing",
    theme: "Spec Arena",
    description: "Unit/async/UI tests ושיפור אמינות קוד.",
    topicCoverage: ["XCTest", "Swift Testing", "unit tests", "async tests", "UI tests", "test doubles", "coverage"],
    badge: "Quality Sentinel",
  },
  {
    id: 28,
    name: "Debugging",
    theme: "Trace Lab",
    description: "איתור תקלות עם breakpoints, LLDB וניתוח קריסות.",
    topicCoverage: ["breakpoints", "LLDB", "logging", "stack traces", "crash analysis", "debug workflow"],
    badge: "Bug Hunter",
  },
  {
    id: 29,
    name: "Performance",
    theme: "Optimization Forge",
    description: "פרופיילינג ושיפור ביצועים עם Instruments.",
    topicCoverage: ["Instruments", "profiling", "time complexity", "memory profiling", "optimization workflow"],
    badge: "Performance Tuner",
  },
  {
    id: 30,
    name: "Security",
    theme: "Shield Bastion",
    description: "Keychain, ניהול סודות ואבטחת תקשורת.",
    topicCoverage: ["Keychain", "secure storage", "secrets management", "certificate pinning basics", "security best practices"],
    badge: "Security Warden",
  },
  {
    id: 31,
    name: "Accessibility & Localization",
    theme: "Global Plaza",
    description: "נגישות, Dynamic Type, RTL ותרגום אפליקציה.",
    topicCoverage: ["VoiceOver", "Dynamic Type", "accessibility labels", "localization", "RTL/LTR", "i18n testing"],
    badge: "Inclusive Builder",
  },
  {
    id: 32,
    name: "App Lifecycle & Production",
    theme: "Release Command",
    description: "הכנה לפרודקשן: lifecycle, CI/CD, TestFlight ו-release.",
    topicCoverage: ["app lifecycle", "background tasks", "notifications", "CI/CD", "TestFlight", "App Store release"],
    badge: "Production Commander",
  },
];

export function getCourseCatalogEntry(worldId: number): CourseCatalogEntry | undefined {
  return courseCatalog.find((entry) => entry.id === worldId);
}

