import { World } from "@/lib/types";

export const worlds: World[] = [
  {
    id: 1,
    name: "Syntax Fields",
    theme: "Starter Valley",
    description: "Variables, basic types, operators, interpolation, and first outputs.",
    topicCoverage: [
      "let",
      "var",
      "String",
      "Int",
      "Double",
      "Bool",
      "print",
      "comments",
      "operators",
      "interpolation",
    ],
    stages: ["w1-s1", "w1-s2", "w1-s3"],
    enemySet: ["Typo Slime", "Shadow Compiler", "Echo Bat"],
    miniBoss: "Format Warden",
    finalBoss: "Syntax Drake",
    unlockRequirement: { minLevel: 1, requiredWorlds: [] },
    rewardSet: { xp: 280, coins: 140, badge: "Syntax Survivor" },
  },
  {
    id: 2,
    name: "Optional Caverns",
    theme: "Crystal Depths",
    description: "Optionals, unwrapping patterns, and safe access patterns.",
    topicCoverage: [
      "Optional",
      "nil",
      "if let",
      "guard let",
      "optional chaining",
      "nil coalescing",
      "force unwrap",
    ],
    stages: ["w2-s1", "w2-s2", "w2-s3"],
    enemySet: ["Nil Phantom", "Chain Worm", "Panic Crawler"],
    miniBoss: "Guardian of Guard",
    finalBoss: "Void Optional Hydra",
    unlockRequirement: { minLevel: 2, requiredWorlds: [1] },
    rewardSet: { xp: 360, coins: 170, badge: "Optional Survivor" },
  },
  {
    id: 3,
    name: "Function Forest",
    theme: "Echo Woods",
    description: "Functions, parameters, labels, defaults, and scope.",
    topicCoverage: [
      "func",
      "parameters",
      "return",
      "argument labels",
      "default values",
      "scope",
      "inout",
      "overloading",
    ],
    stages: ["w3-s1", "w3-s2", "w3-s3"],
    enemySet: ["Label Wolf", "Return Sprite", "Scope Hawk"],
    miniBoss: "Overload Keeper",
    finalBoss: "Forest of Signatures",
    unlockRequirement: { minLevel: 3, requiredWorlds: [1, 2] },
    rewardSet: { xp: 430, coins: 200 },
  },
  {
    id: 4,
    name: "Flow Canyon",
    theme: "Forked Cliffs",
    description: "Control flow with conditions, loops, and branch logic.",
    topicCoverage: [
      "if else",
      "switch",
      "for-in",
      "while",
      "repeat-while",
      "break",
      "continue",
    ],
    stages: ["w4-s1", "w4-s2", "w4-s3"],
    enemySet: ["Loop Beetle", "Switch Imp", "Branch Croc"],
    miniBoss: "Canyon Sentinel",
    finalBoss: "Control Titan",
    unlockRequirement: { minLevel: 4, requiredWorlds: [1, 2, 3] },
    rewardSet: { xp: 490, coins: 230 },
  },
  {
    id: 5,
    name: "Collections Kingdom",
    theme: "Vault Plains",
    description: "Arrays, dictionaries, sets, and transformation basics.",
    topicCoverage: [
      "Array",
      "Dictionary",
      "Set",
      "iteration",
      "append remove",
      "contains",
      "map filter basics",
    ],
    stages: ["w5-s1", "w5-s2", "w5-s3"],
    enemySet: ["Array Gnoll", "Set Djinn", "Map Raven"],
    miniBoss: "King of Keys",
    finalBoss: "Collection Colossus",
    unlockRequirement: { minLevel: 5, requiredWorlds: [1, 2, 3, 4] },
    rewardSet: { xp: 560, coins: 260 },
  },
  {
    id: 6,
    name: "Struct City",
    theme: "Foundry District",
    description: "Struct modeling, init, methods, mutating, and observers.",
    topicCoverage: [
      "struct",
      "stored properties",
      "computed properties",
      "methods",
      "mutating",
      "init",
      "property observers",
    ],
    stages: ["w6-s1", "w6-s2", "w6-s3"],
    enemySet: ["Init Golem", "Mutator Fox", "Observer Owl"],
    miniBoss: "City Architect",
    finalBoss: "Steel Struct Prime",
    unlockRequirement: { minLevel: 6, requiredWorlds: [1, 2, 3, 4, 5] },
    rewardSet: { xp: 620, coins: 290 },
  },
  {
    id: 7,
    name: "Class Citadel",
    theme: "Ivory Keep",
    description: "Classes, inheritance, overrides, and reference semantics.",
    topicCoverage: [
      "class",
      "inheritance",
      "override",
      "final",
      "reference types",
      "identity",
      "deinit",
    ],
    stages: ["w7-s1", "w7-s2", "w7-s3"],
    enemySet: ["Reference Shade", "Override Knight", "Identity Wisp"],
    miniBoss: "Final Gatekeeper",
    finalBoss: "Citadel Regent",
    unlockRequirement: { minLevel: 7, requiredWorlds: [1, 2, 3, 4, 5, 6] },
    rewardSet: { xp: 680, coins: 330 },
  },
  {
    id: 8,
    name: "Protocol Temple",
    theme: "Rune Sanctum",
    description: "Protocol conformance, extensions, and composition.",
    topicCoverage: [
      "protocol",
      "conformance",
      "extension",
      "protocol oriented basics",
    ],
    stages: ["w8-s1", "w8-s2", "w8-s3"],
    enemySet: ["Conformance Shade", "Extension Monk", "Trait Sentry"],
    miniBoss: "Temple Archivist",
    finalBoss: "Protocol Oracle",
    unlockRequirement: { minLevel: 8, requiredWorlds: [1, 2, 3, 4, 5, 6, 7] },
    rewardSet: { xp: 740, coins: 360 },
  },
  {
    id: 9,
    name: "Closure Tower",
    theme: "Sky Spire",
    description: "Closures, shorthand args, capture behavior, completion usage.",
    topicCoverage: [
      "closures",
      "trailing closures",
      "shorthand args",
      "capture",
      "sorting closures",
      "completion handlers",
    ],
    stages: ["w9-s1", "w9-s2", "w9-s3"],
    enemySet: ["Capture Spirit", "Trail Serpent", "Sort Falcon"],
    miniBoss: "Tower Curator",
    finalBoss: "Closure Leviathan",
    unlockRequirement: { minLevel: 9, requiredWorlds: [1, 2, 3, 4, 5, 6, 7, 8] },
    rewardSet: { xp: 810, coins: 390 },
  },
  {
    id: 10,
    name: "Error & Async Sea",
    theme: "Storm Coast",
    description: "Error handling and async foundations in modern Swift.",
    topicCoverage: [
      "throw",
      "do catch",
      "try variants",
      "Result basics",
      "async await",
      "Task",
      "MainActor basics",
    ],
    stages: ["w10-s1", "w10-s2", "w10-s3"],
    enemySet: ["Catch Kraken", "Task Siren", "Actor Tidecaller"],
    miniBoss: "Semaphore Warden",
    finalBoss: "Async Maelstrom",
    unlockRequirement: { minLevel: 10, requiredWorlds: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
    rewardSet: { xp: 890, coins: 430 },
  },
  {
    id: 11,
    name: "SwiftUI City",
    theme: "Glass Metropolis",
    description: "Core SwiftUI views, modifiers, navigation, and presentation.",
    topicCoverage: [
      "View",
      "Text",
      "stacks",
      "modifiers",
      "images",
      "buttons",
      "lists",
      "NavigationStack",
      "sheets",
      "alerts",
    ],
    stages: ["w11-s1", "w11-s2", "w11-s3"],
    enemySet: ["Stack Phantom", "Modifier Rogue", "Sheet Phantom"],
    miniBoss: "Navigator Prime",
    finalBoss: "City Renderer",
    unlockRequirement: { minLevel: 11, requiredWorlds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    rewardSet: { xp: 980, coins: 470 },
  },
  {
    id: 12,
    name: "State & Architecture Arena",
    theme: "Signal Colosseum",
    description: "State wrappers, data flow, and practical architecture decisions.",
    topicCoverage: [
      "State",
      "Binding",
      "ObservedObject",
      "StateObject",
      "EnvironmentObject",
      "data flow",
      "component design",
      "mini architecture",
      "real world scenarios",
    ],
    stages: ["w12-s1", "w12-s2", "w12-s3"],
    enemySet: ["State Warden", "Binding Ghost", "Flow Judge"],
    miniBoss: "Arena Arbiter",
    finalBoss: "Architect Eternal",
    unlockRequirement: { minLevel: 12, requiredWorlds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    rewardSet: { xp: 1100, coins: 520, badge: "State Tamer" },
  },
];

export const topicDependencies: Record<string, string[]> = {
  "Optional Caverns": ["Syntax Fields"],
  "Function Forest": ["Syntax Fields"],
  "Flow Canyon": ["Syntax Fields", "Function Forest"],
  "Collections Kingdom": ["Syntax Fields", "Flow Canyon"],
  "Struct City": ["Function Forest", "Collections Kingdom"],
  "Class Citadel": ["Struct City"],
  "Protocol Temple": ["Struct City", "Class Citadel"],
  "Closure Tower": ["Function Forest", "Collections Kingdom"],
  "Error & Async Sea": ["Flow Canyon", "Closure Tower"],
  "SwiftUI City": ["Syntax Fields", "Function Forest"],
  "State & Architecture Arena": ["SwiftUI City", "Struct City", "Class Citadel"],
};
