import { Question } from "@/lib/types";
import { ensureMinimumWorldQuestions } from "@/lib/questions-expanded";

type World1Draft = Omit<
  Question,
  "worldId" | "codeLanguage" | "prerequisites" | "relatedQuestionIds"
> & {
  codeLanguage?: "swift" | "swiftui";
  prerequisites?: string[];
  relatedQuestionIds?: string[];
};

function w1(draft: World1Draft): Question {
  return {
    worldId: 1,
    codeLanguage: draft.codeLanguage ?? "swift",
    prerequisites: draft.prerequisites ?? [],
    relatedQuestionIds: draft.relatedQuestionIds ?? [],
    ...draft,
  };
}

const coreQuestions: Question[] = [
  w1({
    id: "w1-q1",
    stageId: "w1-s1",
    topic: "let / var",
    subtopic: "immutability",
    difficulty: "easy",
    format: "find_bug",
    questionText: "מה הבעיה בקוד הבא?",
    codeSnippet: `let score = 10\nscore = 12`,
    options: [
      "אין בעיה, זה קוד תקין.",
      "אי אפשר לשנות let אחרי אתחול.",
      "צריך להוסיף print כדי שזה יעבוד.",
      "צריך להחליף Int ל-Double.",
    ],
    correctAnswerIndex: 1,
    explanation:
      "let מגדיר קבוע. אחרי שהגדרת ערך ראשון, אי אפשר לשנות אותו. כדי לעדכן ערך צריך var.",
    wrongOptionExplanations: [
      "יש בעיה ברורה: שורה 2 מנסה לבצע reassignment לקבוע.",
      "נכון.",
      "print לא קשור לתקינות assignment.",
      "הטיפוס לא הבעיה כאן; האימוטביליות כן.",
    ],
    hint: "חשוב על ההבדל בין immutable ל-mutable.",
    tags: ["basics", "variables"],
    xpReward: 20,
    retryWeight: 3,
    relatedQuestionIds: ["w1-q24", "w1-q28"],
  }),
  w1({
    id: "w1-q2",
    stageId: "w1-s1",
    topic: "interpolation",
    subtopic: "string building",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה יודפס?",
    codeSnippet: `let name = "Dana"\nlet level = 4\nprint("\\(name) reached level \\(level)")`,
    options: [
      "name reached level level",
      "Dana reached level 4",
      "Dana + level 4",
      "שגיאת קומפילציה",
    ],
    correctAnswerIndex: 1,
    explanation:
      "String interpolation ב-Swift משתמש ב-\\(expr) כדי להכניס ערכים לתוך String.",
    wrongOptionExplanations: [
      "זה היה נכון רק אם לא היה interpolation בכלל.",
      "נכון.",
      "Swift לא מדפיס פלוס כחיבור טקסט בצורה הזאת.",
      "אין כאן שגיאת קומפילציה.",
    ],
    hint: "\\( ... ) בתוך String מפעיל interpolation.",
    tags: ["strings", "output"],
    xpReward: 20,
    retryWeight: 2,
    prerequisites: ["let/var"],
    relatedQuestionIds: ["w1-q13", "w1-q39"],
  }),
  w1({
    id: "w1-q3",
    stageId: "w1-s1",
    topic: "operators",
    subtopic: "comparison",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה הפלט?",
    codeSnippet: `let x = 8\nlet y = 3\nprint(x > y && y > 0)`,
    options: ["true", "false", "8", "שגיאה כי אי אפשר && על Int"],
    correctAnswerIndex: 0,
    explanation:
      "x > y מחזיר true וגם y > 0 מחזיר true, לכן true && true הוא true.",
    wrongOptionExplanations: [
      "נכון.",
      "שני תנאים נכונים ולכן לא false.",
      "print מדפיס Bool כאן, לא מספר.",
      "&& עובד על Bool, והתנאים עצמם כבר Bool.",
    ],
    hint: "בדוק כל תנאי בנפרד ואז חבר עם &&.",
    tags: ["operators", "bool"],
    xpReward: 20,
    retryWeight: 2,
    relatedQuestionIds: ["w1-q12", "w1-q31"],
  }),
  w1({
    id: "w1-q4",
    stageId: "w1-s1",
    topic: "types",
    subtopic: "type safety",
    difficulty: "medium",
    format: "choose_correct_code",
    questionText: "איזה קטע קוד יתקמפל?",
    codeSnippet: `A) let age: Int = "20"\nB) let age: Int = 20\nC) let age = 20.5 as Int\nD) let age: String = 20`,
    options: ["A", "B", "C", "D"],
    correctAnswerIndex: 1,
    explanation:
      "B תקין: הטיפוס Int תואם לערך 20. שאר האפשרויות מערבבות טיפוסים בלי המרה נכונה.",
    wrongOptionExplanations: [
      "A שגוי כי String לא נכנס ל-Int בלי המרה.",
      "נכון.",
      "C לא תקין בתחביר הזה; as Int לא ממיר Double literal כך.",
      "D שגוי: 20 הוא Int ולא String.",
    ],
    hint: "Swift strict לגבי התאמת טיפוסים.",
    tags: ["types", "compiler"],
    xpReward: 25,
    retryWeight: 3,
    prerequisites: ["let/var"],
    relatedQuestionIds: ["w1-q29"],
  }),
  w1({
    id: "w1-q5",
    stageId: "w1-s1",
    topic: "comments",
    subtopic: "syntax",
    difficulty: "easy",
    format: "multiple_choice",
    questionText: "איזו צורה תקינה להערת שורה אחת ב-Swift?",
    codeSnippet: "",
    options: ["# note", "// note", "<!-- note -->", "** note"],
    correctAnswerIndex: 1,
    explanation: "להערת שורה בודדת משתמשים ב-//.",
    wrongOptionExplanations: [
      "# לא משמש כהערת קוד רגילה ב-Swift.",
      "נכון.",
      "זו תחביר HTML, לא Swift.",
      "לא קיים תחביר כזה ב-Swift.",
    ],
    hint: "Swift דומה ל-C style comments.",
    tags: ["syntax", "comments"],
    xpReward: 15,
    retryWeight: 1,
    relatedQuestionIds: ["w1-q22", "w1-q34"],
  }),
  w1({
    id: "w1-q6",
    stageId: "w1-s1",
    topic: "output",
    subtopic: "print and expressions",
    difficulty: "medium",
    format: "complete_code",
    questionText: "השלם את החסר כדי להדפיס 9",
    codeSnippet: `let a = 4\nlet b = 5\nprint(___)`,
    options: ["a + b", "\"a+b\"", "a, b", "a ++ b"],
    correctAnswerIndex: 0,
    explanation: "כדי להדפיס 9 צריך ביטוי חשבוני a + b.",
    wrongOptionExplanations: [
      "נכון.",
      "זה String מילולי ולא חישוב.",
      "זה לא ביטוי שמחזיר 9 בשימוש הזה.",
      "++ לא קיים ב-Swift מודרני.",
    ],
    hint: "print מקבל expression, לא רק literal.",
    tags: ["print", "operators"],
    xpReward: 25,
    retryWeight: 2,
    prerequisites: ["operators"],
    relatedQuestionIds: ["w1-q10"],
  }),
  w1({
    id: "w1-q7",
    stageId: "w1-s1",
    topic: "Bool",
    subtopic: "logic",
    difficulty: "medium",
    format: "code_vs_concept",
    questionText: "איזה מושג הקוד הבא מדגים?",
    codeSnippet: `let isSwiftFun = true\nif isSwiftFun {\n  print("Yes")\n}`,
    options: [
      "Type inference",
      "Boolean condition",
      "Optional chaining",
      "Property observer",
    ],
    correctAnswerIndex: 1,
    explanation: "if מקבל תנאי בוליאני, והמשתנה isSwiftFun הוא Bool.",
    wrongOptionExplanations: [
      "יש inference בשורה הראשונה, אבל העיקר הוא תנאי בוליאני.",
      "נכון.",
      "אין כאן Optional בכלל.",
      "אין כאן willSet/didSet.",
    ],
    hint: "תתמקד בתנאי של if.",
    tags: ["bool", "if"],
    xpReward: 30,
    retryWeight: 2,
    prerequisites: ["types"],
    relatedQuestionIds: ["w1-q12", "w1-q20"],
  }),
  w1({
    id: "w1-q8",
    stageId: "w1-s1",
    topic: "operators",
    subtopic: "assignment vs equality",
    difficulty: "hard",
    format: "find_bug",
    questionText: "למה הקוד הבא לא תקין?",
    codeSnippet: `let a = 5\nif a = 5 {\n  print("match")\n}`,
    options: [
      "אי אפשר להשתמש ב-if ב-Swift",
      "צריך == להשוואה ולא =",
      "print חייב להיות מחוץ ל-if",
      "צריך להפוך את a ל-var",
    ],
    correctAnswerIndex: 1,
    explanation:
      "בתנאי משתמשים בהשוואה (`==`) ולא בהשמה (`=`). לכן זו שגיאת קומפילציה.",
    wrongOptionExplanations: [
      "if כמובן קיים ב-Swift.",
      "נכון.",
      "print יכול להיות בתוך if ללא בעיה.",
      "אין צורך ב-var לשם השוואה.",
    ],
    hint: "הבדל קריטי: assignment מול comparison.",
    tags: ["operators", "if"],
    xpReward: 35,
    retryWeight: 4,
    prerequisites: ["operators"],
    relatedQuestionIds: ["w1-q17", "w1-q30"],
  }),
  w1({
    id: "w1-q9",
    stageId: "w1-s1",
    topic: "String",
    subtopic: "concatenation",
    difficulty: "medium",
    format: "mini_refactor",
    questionText: "מה הדרך הנקייה יותר לבנות את המחרוזת?",
    codeSnippet: `let user = "Noa"\nlet score = 12\nlet label = user + " has score " + String(score)`,
    options: [
      "להשאיר בדיוק כך, זו הדרך המועדפת תמיד",
      "להחליף ל-String interpolation",
      "להמיר score ל-Double לפני החיבור",
      "להשתמש ב-NSArray",
    ],
    correctAnswerIndex: 1,
    explanation:
      "Interpolation (\"\\(user) has score \\(score)\") קריא יותר ופחות רגיש לטעויות המרה.",
    wrongOptionExplanations: [
      "אפשרי, אבל פחות קריא לעומת interpolation.",
      "נכון.",
      "אין צורך ב-Double פה.",
      "NSArray לא קשור ליצירת String.",
    ],
    hint: "חפש סגנון Swift-י קריא יותר.",
    tags: ["strings", "style"],
    xpReward: 30,
    retryWeight: 2,
    prerequisites: ["interpolation"],
    relatedQuestionIds: ["w1-q36"],
  }),
];

const outputQuestions: Question[] = [
  w1({
    id: "w1-q10",
    stageId: "w1-s1",
    topic: "operators",
    subtopic: "arithmetic",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה יודפס?",
    codeSnippet: `let a = 3\nlet b = 4\nprint(a * b + 2)`,
    options: ["12", "14", "24", "שגיאת קומפילציה"],
    correctAnswerIndex: 1,
    explanation: "כפל מתבצע לפני חיבור: 3*4 = 12 ואז +2 = 14.",
    wrongOptionExplanations: [
      "זו תוצאה של כפל בלבד, בלי החיבור האחרון.",
      "נכון.",
      "אין כאן כפל נוסף ב-2.",
      "הקוד תקין לחלוטין.",
    ],
    hint: "סדר פעולות חשבון עדיין חשוב גם ב-Swift.",
    tags: ["operators", "math"],
    xpReward: 18,
    retryWeight: 2,
    relatedQuestionIds: ["w1-q14", "w1-q35"],
  }),
  w1({
    id: "w1-q11",
    stageId: "w1-s1",
    topic: "var",
    subtopic: "mutation",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה יודפס בסוף?",
    codeSnippet: `var coins = 2\ncoins = coins + 4\nprint(coins)`,
    options: ["2", "4", "6", "שגיאה כי coins הוא let"],
    correctAnswerIndex: 2,
    explanation: "הערך מתחיל ב-2 ומעודכן ל-6.",
    wrongOptionExplanations: [
      "זה הערך לפני העדכון.",
      "הוספנו 4 לערך 2, לא החלפנו אותו ל-4.",
      "נכון.",
      "coins מוגדר כ-var ולכן שינוי מותר.",
    ],
    hint: "עקוב אחרי הערך שורה-שורה.",
    tags: ["variables", "state"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q12",
    stageId: "w1-s1",
    topic: "Bool",
    subtopic: "or operator",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה הפלט?",
    codeSnippet: `let hasKey = false\nlet hasCode = true\nprint(hasKey || hasCode)`,
    options: ["true", "false", "0", "שגיאת קומפילציה"],
    correctAnswerIndex: 0,
    explanation: "ב-OR מספיק תנאי אחד true כדי לקבל true.",
    wrongOptionExplanations: [
      "נכון.",
      "false || true מחזיר true.",
      "הפלט הוא Bool ולא מספר.",
      "הביטוי תקין.",
    ],
    hint: "|| מחזיר true אם לפחות צד אחד true.",
    tags: ["bool", "logic"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q13",
    stageId: "w1-s1",
    topic: "interpolation",
    subtopic: "mixed values",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה יודפס?",
    codeSnippet: `let points = 7\nprint("Points: \\(points + 3)")`,
    options: ["Points: points + 3", "Points: 10", "Points: 73", "שגיאת קומפילציה"],
    correctAnswerIndex: 1,
    explanation: "אפשר לשים ביטוי מלא בתוך interpolation, ולכן 7+3 => 10.",
    wrongOptionExplanations: [
      "כאן יש interpolation אמיתי, לא טקסט קשיח.",
      "נכון.",
      "אין כאן חיבור טקסט של '7' ו-'3'.",
      "הקוד תקין.",
    ],
    hint: "בתוך \\( ) אפשר לחשב ערכים, לא רק להדפיס משתנה.",
    tags: ["strings", "interpolation"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q14",
    stageId: "w1-s1",
    topic: "operators",
    subtopic: "precedence",
    difficulty: "medium",
    format: "output_prediction",
    questionText: "מה ייצא מההדפסה?",
    codeSnippet: `print(2 + 3 * 2)`,
    options: ["10", "8", "12", "שגיאת קומפילציה"],
    correctAnswerIndex: 1,
    explanation: "כפל קודם לחיבור: 3*2=6 ואז 2+6=8.",
    wrongOptionExplanations: [
      "זו תוצאה של (2+3)*2, לא של הביטוי הנוכחי.",
      "נכון.",
      "אין כאן חיבור של כל המספרים ואז כפל נוסף.",
      "אין שום שגיאת תחביר.",
    ],
    hint: "אם חשוב לך סדר אחר, הוסף סוגריים.",
    tags: ["operators", "math"],
    xpReward: 22,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q15",
    stageId: "w1-s2",
    topic: "String",
    subtopic: "count",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה הפלט?",
    codeSnippet: `let word = "Swift"\nprint(word.count)`,
    options: ["4", "5", "6", "שגיאת קומפילציה"],
    correctAnswerIndex: 1,
    explanation: "במילה Swift יש 5 תווים, לכן count מחזיר 5.",
    wrongOptionExplanations: [
      "חסר תו אחד בספירה.",
      "נכון.",
      "אין 6 תווים במחרוזת הזו.",
      "הקוד תקין.",
    ],
    hint: "count מחזיר את מספר התווים במחרוזת.",
    tags: ["string", "api"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q16",
    stageId: "w1-s2",
    topic: "Int",
    subtopic: "integer division",
    difficulty: "medium",
    format: "output_prediction",
    questionText: "מה יודפס?",
    codeSnippet: `let value = 7 / 2\nprint(value)`,
    options: ["3", "3.5", "4", "שגיאת קומפילציה"],
    correctAnswerIndex: 0,
    explanation: "כששני האופרנדים Int, Swift מבצע חלוקה שלמה ומחזיר 3.",
    wrongOptionExplanations: [
      "נכון.",
      "3.5 היה מתקבל רק עם Double.",
      "Swift לא מעגל כלפי מעלה כאן.",
      "אין שגיאה; זו חלוקה שלמה תקינה.",
    ],
    hint: "לחלוקה עם שבר השתמש ב-Double.",
    tags: ["int", "math"],
    xpReward: 22,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q17",
    stageId: "w1-s2",
    topic: "operators",
    subtopic: "equality",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה הפלט?",
    codeSnippet: `let a = 3\nlet b = 3\nprint(a == b)`,
    options: ["true", "false", "3", "שגיאת קומפילציה"],
    correctAnswerIndex: 0,
    explanation: "a ו-b שווים, ולכן השוואת == מחזירה true.",
    wrongOptionExplanations: [
      "נכון.",
      "התנאי נכון ולכן לא false.",
      "print מדפיס Bool במקרה הזה.",
      "הקוד תקין.",
    ],
    hint: "== מחזיר Bool בהתאם לשוויון הערכים.",
    tags: ["operators", "comparison"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q18",
    stageId: "w1-s2",
    topic: "operators",
    subtopic: "compound assignment",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה יודפס?",
    codeSnippet: `var xp = 1\nxp += 4\nprint(xp)`,
    options: ["1", "4", "5", "שגיאת קומפילציה"],
    correctAnswerIndex: 2,
    explanation: "xp += 4 שקול ל-xp = xp + 4, לכן נקבל 5.",
    wrongOptionExplanations: [
      "זה הערך ההתחלתי לפני ההוספה.",
      "הביטוי מוסיף 4 לערך, לא מחליף אותו ב-4.",
      "נכון.",
      "התחביר תקין.",
    ],
    hint: "+= תמיד משתמש בערך הנוכחי ואז מוסיף אליו.",
    tags: ["operators", "assignment"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q19",
    stageId: "w1-s2",
    topic: "operators",
    subtopic: "remainder",
    difficulty: "medium",
    format: "output_prediction",
    questionText: "מה הפלט?",
    codeSnippet: `print(17 % 5)`,
    options: ["2", "3", "5", "שגיאת קומפילציה"],
    correctAnswerIndex: 0,
    explanation: "17 חלקי 5 נותן שארית 2.",
    wrongOptionExplanations: [
      "נכון.",
      "3 הוא תוצאת החלוקה השלמה, לא השארית.",
      "5 הוא המחלק, לא התוצאה.",
      "הקוד חוקי.",
    ],
    hint: "% מחזיר שארית חלוקה.",
    tags: ["operators", "math"],
    xpReward: 22,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q20",
    stageId: "w1-s2",
    topic: "Bool",
    subtopic: "negation",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה יודפס?",
    codeSnippet: `let isReady = false\nprint(!isReady)`,
    options: ["true", "false", "!false", "שגיאת קומפילציה"],
    correctAnswerIndex: 0,
    explanation: "! הופך false ל-true.",
    wrongOptionExplanations: [
      "נכון.",
      "הערך ההפוך של false הוא true.",
      "print מדפיס את הערך המחושב, לא את הטקסט של הביטוי.",
      "אין שגיאה.",
    ],
    hint: "! הוא logical NOT.",
    tags: ["bool", "operators"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q21",
    stageId: "w1-s2",
    topic: "operators",
    subtopic: "mixed arithmetic",
    difficulty: "medium",
    format: "output_prediction",
    questionText: "מה יופיע?",
    codeSnippet: `let value = (2 + 3) * 4\nprint(value - 5)`,
    options: ["15", "20", "25", "שגיאת קומפילציה"],
    correctAnswerIndex: 0,
    explanation: "(2+3)=5, כפול 4 זה 20, פחות 5 זה 15.",
    wrongOptionExplanations: [
      "נכון.",
      "זה הערך לפני החיסור האחרון.",
      "אין כאן פעולה שמייצרת 25.",
      "הקוד חוקי.",
    ],
    hint: "פרק את הביטוי לשלבים קצרים.",
    tags: ["operators", "math"],
    xpReward: 22,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q22",
    stageId: "w1-s2",
    topic: "comments",
    subtopic: "ignored code",
    difficulty: "easy",
    format: "output_prediction",
    questionText: "מה יודפס?",
    codeSnippet: `let hp = 9\n// hp = 1\nprint(hp)`,
    options: ["1", "9", "0", "שגיאת קומפילציה"],
    correctAnswerIndex: 1,
    explanation: "שורת ההערה לא רצה, לכן hp נשאר 9.",
    wrongOptionExplanations: [
      "hp לא עודכן כי השורה בהערה.",
      "נכון.",
      "לא קיימת כאן פעולה שמאפסת את hp.",
      "הקוד תקין.",
    ],
    hint: "קוד בתוך הערה לא משפיע על ריצה.",
    tags: ["comments", "output"],
    xpReward: 18,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q23",
    stageId: "w1-s2",
    topic: "String",
    subtopic: "concatenation",
    difficulty: "medium",
    format: "output_prediction",
    questionText: "מה הפלט?",
    codeSnippet: `let left = "Swift"\nlet right = "Quest"\nprint(left + " " + right)`,
    options: ["SwiftQuest", "Swift Quest", "left right", "שגיאת קומפילציה"],
    correctAnswerIndex: 1,
    explanation: "המחרוזת באמצע היא רווח, ולכן הפלט כולל רווח בין המילים.",
    wrongOptionExplanations: [
      "זה היה נכון בלי ה-\" \" באמצע.",
      "נכון.",
      "Swift מחבר את הערכים של המשתנים, לא את השמות שלהם.",
      "הקוד תקין.",
    ],
    hint: "שים לב לרווח המפורש בחיבור המחרוזות.",
    tags: ["string", "operators"],
    xpReward: 22,
    retryWeight: 2,
  }),
];

const advancedQuestions: Question[] = [
  w1({
    id: "w1-q24",
    stageId: "w1-s2",
    topic: "let / var",
    subtopic: "mutable declaration",
    difficulty: "medium",
    format: "choose_correct_code",
    questionText: "איזה קטע קוד נכון אם המטרה היא לעדכן את score אחר כך?",
    codeSnippet: `A) let score = 0\nB) var score = 0\nC) let score: String = 0\nD) let score = "0"`,
    options: ["A", "B", "C", "D"],
    correctAnswerIndex: 1,
    explanation: "רק var מאפשר שינוי ערך בהמשך.",
    wrongOptionExplanations: [
      "let לא ניתן לשינוי.",
      "נכון.",
      "יש גם בעיית טיפוס וגם קבוע.",
      "String לא מתאים אם score אמור להיות מספר.",
    ],
    hint: "שאל את עצמך אם הערך אמור להשתנות בהמשך.",
    tags: ["variables", "types"],
    xpReward: 25,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q25",
    stageId: "w1-s2",
    topic: "print",
    subtopic: "syntax",
    difficulty: "medium",
    format: "find_bug",
    questionText: "איפה הבאג?",
    codeSnippet: `let city = "Haifa"\nprint(city`,
    options: [
      "אין באג",
      "חסר סוגר סוגר בסוף print",
      "צריך var במקום let",
      "צריך להגדיר city כ-Int",
    ],
    correctAnswerIndex: 1,
    explanation: "בקריאה לפונקציה צריך לסגור את הסוגריים.",
    wrongOptionExplanations: [
      "יש שגיאת תחביר ברורה.",
      "נכון.",
      "let תקין כאן כי לא משנים את הערך.",
      "city הוא טקסט ולכן String מתאים.",
    ],
    hint: "בדוק איזון סוגריים בקריאות פונקציה.",
    tags: ["print", "syntax"],
    xpReward: 25,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q26",
    stageId: "w1-s2",
    topic: "interpolation",
    subtopic: "complete snippet",
    difficulty: "medium",
    format: "complete_code",
    questionText: "מה צריך להשלים במקום ___ כדי לקבל: Level 8",
    codeSnippet: `let level = 8\nprint("Level ___")`,
    options: ["\\(level)", "{level}", "$level", "level"],
    correctAnswerIndex: 0,
    explanation: "ב-Swift interpolation משתמש ב-\\(expression).",
    wrongOptionExplanations: [
      "נכון.",
      "זה סגנון של שפות אחרות, לא Swift.",
      "תחביר כזה לא קיים ב-Swift Strings.",
      "זה ידפיס את המילה level, לא את הערך.",
    ],
    hint: "זכור את התחביר המדויק: backslash + parentheses.",
    tags: ["interpolation", "strings"],
    xpReward: 25,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q27",
    stageId: "w1-s2",
    topic: "types",
    subtopic: "type inference",
    difficulty: "medium",
    format: "code_vs_concept",
    questionText: "איזה מושג הקוד הבא מציג?",
    codeSnippet: `let speed = 90`,
    options: ["Optional binding", "Type inference", "Protocol conformance", "Reference counting"],
    correctAnswerIndex: 1,
    explanation: "לא הוגדר טיפוס מפורש, ו-Swift מסיק Int לפי הערך.",
    wrongOptionExplanations: [
      "אין כאן Optional בכלל.",
      "נכון.",
      "לא מופיע protocol בקוד.",
      "ARC לא קשור לקוד הזה.",
    ],
    hint: "כאשר לא כתבת טיפוס, Swift מנסה להסיק אותו.",
    tags: ["types", "inference"],
    xpReward: 24,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q28",
    stageId: "w1-s2",
    topic: "let / var",
    subtopic: "code comparison",
    difficulty: "medium",
    format: "code_comparison",
    questionText: "מה ההבדל המרכזי בין A ל-B?",
    codeSnippet: `A) let lives = 3\nB) var lives = 3`,
    options: [
      "A מגדיר Double ו-B מגדיר Int",
      "A קבוע, B ניתן לשינוי",
      "A מהיר יותר בקומפילציה",
      "אין הבדל",
    ],
    correctAnswerIndex: 1,
    explanation: "let יוצר קבוע, var יוצר משתנה mutable.",
    wrongOptionExplanations: [
      "הטיפוס לא נקבע לפי let/var אלא לפי הערך או annotation.",
      "נכון.",
      "זו לא הטענה הנכונה כאן.",
      "יש הבדל מהותי ביכולת שינוי הערך.",
    ],
    hint: "תחשוב על שינוי ערך לאחר האתחול.",
    tags: ["variables", "comparison"],
    xpReward: 24,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q29",
    stageId: "w1-s2",
    topic: "types",
    subtopic: "double literal",
    difficulty: "medium",
    format: "choose_correct_code",
    questionText: "איזה קוד מגדיר Double בצורה תקינה?",
    codeSnippet: `A) let price: Double = 9.99\nB) let price: Double = "9.99"\nC) let price: Int = 9.99\nD) let price = 9,99`,
    options: ["A", "B", "C", "D"],
    correctAnswerIndex: 0,
    explanation: "Double מקבל מספר עשרוני נקודה, לא String ולא Int.",
    wrongOptionExplanations: [
      "נכון.",
      "זה String ולא מספר.",
      "Int לא יכול להכיל ערך עם נקודה עשרונית.",
      "Swift משתמש בנקודה עשרונית, לא פסיק.",
    ],
    hint: "שים לב גם לטיפוס וגם ל-literal syntax.",
    tags: ["types", "double"],
    xpReward: 25,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q30",
    stageId: "w1-s2",
    topic: "types",
    subtopic: "string + int",
    difficulty: "medium",
    format: "find_bug",
    questionText: "למה הקוד הבא נופל בקומפילציה?",
    codeSnippet: `let amount = 4\nprint("Total: " + amount)`,
    options: [
      "אי אפשר לחבר String עם Int ישירות",
      "print לא יכול לקבל חיבור",
      "צריך let amount = \"4\" תמיד",
      "אין בעיה, זה קוד תקין",
    ],
    correctAnswerIndex: 0,
    explanation: "צריך להמיר את amount ל-String או להשתמש ב-interpolation.",
    wrongOptionExplanations: [
      "נכון.",
      "print כן יכול לקבל חיבור תקין של מחרוזות.",
      "אפשר גם להשאיר Int ולהשתמש ב-\\(amount).",
      "יש בעיית טיפוס ברורה.",
    ],
    hint: "פתרון נקי: print(\"Total: \\(amount)\").",
    tags: ["types", "strings"],
    xpReward: 26,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q31",
    stageId: "w1-s3",
    topic: "Bool",
    subtopic: "and operator",
    difficulty: "hard",
    format: "complete_code",
    questionText: "השלם את האופרטור המתאים במקום ___",
    codeSnippet: `let hasTicket = true\nlet hasID = false\nprint(hasTicket ___ hasID)`,
    options: ["&&", "||", "==", "%"],
    correctAnswerIndex: 0,
    explanation: "אם רוצים ששני התנאים יידרשו ביחד, משתמשים ב-&&.",
    wrongOptionExplanations: [
      "נכון.",
      "|| בודק אם לפחות אחד true.",
      "== בודק שוויון בין הערכים, לא צירוף תנאים ללוגיקת כניסה.",
      "% הוא אופרטור חשבוני.",
    ],
    hint: "AND = שני תנאים חייבים להתקיים.",
    tags: ["bool", "logic"],
    xpReward: 30,
    retryWeight: 4,
  }),
  w1({
    id: "w1-q32",
    stageId: "w1-s3",
    topic: "print",
    subtopic: "mini refactor",
    difficulty: "hard",
    format: "mini_refactor",
    questionText: "איזה refactor יותר Swift-י לקוד הבא?",
    codeSnippet: `let user = "Eli"\nlet text = "Hello " + user\nprint(text)`,
    options: [
      "להשאיר כך, אין שיפור אפשרי",
      "להחליף ל-print(\"Hello \\(user)\")",
      "להחליף את user ל-Int",
      "למחוק את print",
    ],
    correctAnswerIndex: 1,
    explanation: "Interpolation ישיר בתוך print קצר יותר וקריא יותר.",
    wrongOptionExplanations: [
      "הקוד עובד, אבל אפשר לפשט אותו.",
      "נכון.",
      "אין הצדקה לשינוי טיפוס.",
      "המטרה היא עדיין להדפיס פלט.",
    ],
    hint: "פחות משתני ביניים כשאין בהם צורך.",
    tags: ["print", "style"],
    xpReward: 30,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q33",
    stageId: "w1-s3",
    topic: "types",
    subtopic: "bool declaration",
    difficulty: "hard",
    format: "find_bug",
    questionText: "מה שגוי בשורה הבאה?",
    codeSnippet: `let isOn: Bool = "true"`,
    options: [
      "אין בעיה",
      "Bool לא מקבל String",
      "צריך var במקום let",
      "Bool לא קיים ב-Swift",
    ],
    correctAnswerIndex: 1,
    explanation: "Bool חייב לקבל true/false ממש, לא מחרוזת טקסט.",
    wrongOptionExplanations: [
      "יש כאן mismatch בין הטיפוס לערך.",
      "נכון.",
      "let/var לא פותר את בעיית הטיפוס.",
      "Bool בהחלט קיים בשפה.",
    ],
    hint: "\"true\" שונה מהערך true.",
    tags: ["types", "bool"],
    xpReward: 30,
    retryWeight: 4,
  }),
  w1({
    id: "w1-q34",
    stageId: "w1-s3",
    topic: "comments",
    subtopic: "block comments",
    difficulty: "medium",
    format: "choose_correct_code",
    questionText: "איזה קטע משתמש נכון בהערת בלוק?",
    codeSnippet: `A) /* note */\nB) <!-- note -->\nC) # note #\nD) ** note **`,
    options: ["A", "B", "C", "D"],
    correctAnswerIndex: 0,
    explanation: "ב-Swift הערת בלוק היא /* ... */.",
    wrongOptionExplanations: [
      "נכון.",
      "תחביר HTML, לא Swift.",
      "לא תחביר תקין להערה.",
      "לא קיים ב-Swift.",
    ],
    hint: "יש שני סוגי הערות בסיסיים: // ו-/* */.",
    tags: ["comments", "syntax"],
    xpReward: 24,
    retryWeight: 2,
  }),
  w1({
    id: "w1-q35",
    stageId: "w1-s3",
    topic: "operators",
    subtopic: "concept",
    difficulty: "hard",
    format: "code_vs_concept",
    questionText: "איזה עיקרון מודגם כאן?",
    codeSnippet: `let result = 10 - 2 * 3`,
    options: ["Optional binding", "Operator precedence", "Function overloading", "Protocol conformance"],
    correctAnswerIndex: 1,
    explanation: "כפל מתבצע לפני חיסור כי יש קדימות אופרטורים.",
    wrongOptionExplanations: [
      "אין כאן Optional.",
      "נכון.",
      "אין פונקציות בכלל בדוגמה.",
      "אין protocol בקוד הזה.",
    ],
    hint: "קדימות קובעת אילו פעולות מתבצעות קודם.",
    tags: ["operators", "concept"],
    xpReward: 30,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q36",
    stageId: "w1-s3",
    topic: "String",
    subtopic: "comparison",
    difficulty: "hard",
    format: "code_comparison",
    questionText: "מה ההבדל בין A ל-B?",
    codeSnippet: `A) print("Score: \\(score)")\nB) print("Score: " + String(score))`,
    options: [
      "A תקין ו-B לא תקין",
      "A ו-B תקינים, A לרוב קריא יותר",
      "B מהיר יותר תמיד",
      "A מתאים רק ל-Double",
    ],
    correctAnswerIndex: 1,
    explanation: "שתי האפשרויות חוקיות; interpolation נחשב לרוב נקי וקריא יותר.",
    wrongOptionExplanations: [
      "B גם תקין כשממירים ל-String.",
      "נכון.",
      "אין כלל כזה של מהירות תמידית כאן.",
      "A מתאים לכל ערך שניתן להציג כמחרוזת.",
    ],
    hint: "בדוק תקינות מול קריאות, לא רק תוצאה סופית.",
    tags: ["string", "style"],
    xpReward: 30,
    retryWeight: 3,
  }),
  w1({
    id: "w1-q37",
    stageId: "w1-s3",
    topic: "syntax",
    subtopic: "undeclared symbol",
    difficulty: "hard",
    format: "find_bug",
    questionText: "למה הקוד לא מתקמפל?",
    codeSnippet: `let hp = 10\nprint(health)`,
    options: [
      "כי print לא עובד עם מספרים",
      "כי health לא מוגדר",
      "כי hp חייב להיות var",
      "אין בעיה בקוד",
    ],
    correctAnswerIndex: 1,
    explanation: "יש כאן שימוש במזהה שלא הוגדר (health במקום hp).",
    wrongOptionExplanations: [
      "print כן עובד עם מספרים.",
      "נכון.",
      "אין דרישה לשנות hp כאן.",
      "יש שגיאת שם משתנה.",
    ],
    hint: "בדוק עקביות בשמות משתנים.",
    tags: ["compiler", "variables"],
    xpReward: 32,
    retryWeight: 4,
  }),
  w1({
    id: "w1-q38",
    stageId: "w1-s3",
    topic: "operators",
    subtopic: "complete remainder",
    difficulty: "hard",
    format: "complete_code",
    questionText: "השלם ביטוי שיבדוק אם number זוגי",
    codeSnippet: `let number = 14\nlet isEven = (number ___ 2) == 0`,
    options: ["%", "/", "*", "+"],
    correctAnswerIndex: 0,
    explanation: "בדיקת זוגיות נעשית עם שארית חלוקה ב-2.",
    wrongOptionExplanations: [
      "נכון.",
      "חלוקה לא בודקת זוגיות ישירות.",
      "כפל לא רלוונטי כאן.",
      "חיבור לא בודק שארית.",
    ],
    hint: "אם אין שארית בחלוקה ב-2, המספר זוגי.",
    tags: ["operators", "logic"],
    xpReward: 32,
    retryWeight: 4,
  }),
  w1({
    id: "w1-q39",
    stageId: "w1-s3",
    topic: "interpolation",
    subtopic: "choose correct snippet",
    difficulty: "hard",
    format: "choose_correct_code",
    questionText: "איזה snippet ידפיס: User: Maya",
    codeSnippet: `A) let user = "Maya"; print("User: \\(user)")\nB) let user = "Maya"; print("User: \${user}")\nC) let user = "Maya"; print("User: " + user + )\nD) let user = "Maya"; print(User: user)`,
    options: ["A", "B", "C", "D"],
    correctAnswerIndex: 0,
    explanation: "רק A משתמש בתחביר interpolation נכון של Swift.",
    wrongOptionExplanations: [
      "נכון.",
      "${...} הוא לא תחביר Swift.",
      "יש כאן שגיאת תחביר (פלוס ללא ערך נוסף).",
      "הקריאה ל-print בתחביר לא חוקי.",
    ],
    hint: "התחביר הנכון: \"... \\(value) ...\".",
    tags: ["interpolation", "syntax"],
    xpReward: 34,
    retryWeight: 4,
  }),
  w1({
    id: "w1-q40",
    stageId: "w1-s3",
    topic: "refactor",
    subtopic: "clean code",
    difficulty: "hard",
    format: "mini_refactor",
    questionText: "מה הדרך הפשוטה יותר לקוד הבא?",
    codeSnippet: `let count = 3\nlet message = "Count: \\(count)"\nprint(message)`,
    options: [
      "print(\"Count: \\(count)\")",
      "let message = count",
      "print(count + message)",
      "אסור להשתמש ב-interpolation בתוך print",
    ],
    correctAnswerIndex: 0,
    explanation: "אין צורך במשתנה message אם משתמשים בו פעם אחת בלבד.",
    wrongOptionExplanations: [
      "נכון.",
      "count הוא Int ולכן לא מחליף String כזה.",
      "לא ניתן לחבר Int ו-String כך.",
      "מותר לחלוטין להשתמש ב-interpolation בתוך print.",
    ],
    hint: "פשט קוד כשאין ערך אמיתי למשתנה ביניים.",
    tags: ["style", "refactor"],
    xpReward: 34,
    retryWeight: 3,
  }),
];

const bossQuestions: Question[] = [
  w1({
    id: "w1-boss-1",
    stageId: "w1-boss",
    topic: "Syntax Mix",
    subtopic: "boss mix",
    difficulty: "boss",
    format: "output_prediction",
    questionText: "בוס: מה יודפס בסוף?",
    codeSnippet: `var hp = 10\nhp = hp - 3\nlet hero = "Lia"\nprint("\\(hero): \\(hp)")`,
    options: ["Lia: 10", "Lia: 7", "hero: hp", "שגיאת קומפילציה"],
    correctAnswerIndex: 1,
    explanation:
      "hp התחיל ב-10 ואז ירד ל-7. interpolation מציג את הערכים בפועל.",
    wrongOptionExplanations: [
      "hp עודכן לפני ההדפסה.",
      "נכון.",
      "זו תוצאה ללא interpolation.",
      "הקוד תקין.",
    ],
    hint: "עקוב אחרי השינוי ב-var לפני print.",
    tags: ["boss", "mixed"],
    xpReward: 45,
    retryWeight: 4,
    prerequisites: ["let/var", "interpolation", "operators"],
    relatedQuestionIds: ["w1-q11", "w1-q13", "w1-q19"],
  }),
  w1({
    id: "w1-boss-2",
    stageId: "w1-boss",
    topic: "Syntax Mix",
    subtopic: "logic + output",
    difficulty: "boss",
    format: "find_bug",
    questionText: "בוס: איפה השגיאה הקריטית בקוד?",
    codeSnippet: `let minLevel = 5\nlet playerLevel = 6\nif playerLevel >= minLevel {\n  print("Access")\n}\nprint("Ready: " + playerLevel)`,
    options: [
      "אי אפשר להשתמש ב->= בתוך if",
      "צריך לסגור את הסוגר המסולסל לפני print",
      "חיבור String עם Int בשורה האחרונה לא תקין",
      "אין שום שגיאה",
    ],
    correctAnswerIndex: 2,
    explanation:
      "שורת ה-print האחרונה מנסה לחבר מחרוזת עם Int ישירות. צריך interpolation או String(playerLevel).",
    wrongOptionExplanations: [
      ">= תקין לחלוטין ב-Swift.",
      "הסוגריים והבלוק כתובים נכון.",
      "נכון.",
      "יש שגיאת טיפוס ברורה בשורה האחרונה.",
    ],
    hint: "בדוק התאמת טיפוסים בביטויי String.",
    tags: ["boss", "types", "logic"],
    xpReward: 50,
    retryWeight: 5,
    prerequisites: ["types", "operators", "interpolation"],
    relatedQuestionIds: ["w1-q30", "w1-q36", "w1-q39"],
  }),
];

const baseQuestionBank: Question[] = [
  ...coreQuestions,
  ...outputQuestions,
  ...advancedQuestions,
  ...bossQuestions,
];

export const questionBank: Question[] = ensureMinimumWorldQuestions(baseQuestionBank, 100);

export const world1QuestionIds = questionBank
  .filter((question) => question.worldId === 1)
  .map((question) => question.id);
